<a href="https://colab.research.google.com/github/Christy260703/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

#flatten
a.flatten()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#sort
#create a 3*3 matrix

a = np.array([[3,4,1],[5,3,1],[6,9,8]])
print(a)
print("\n")
b = np.sort(a,axis=0)
print(b)
print("\n")
b = np.sort(a,axis=1)
print(b)
print("\n")
c = np.argsort(a,axis=1)
print(c)



[[3 4 1]
 [5 3 1]
 [6 9 8]]


[[3 3 1]
 [5 4 1]
 [6 9 8]]


[[1 3 4]
 [1 3 5]
 [6 8 9]]


[[2 0 1]
 [2 1 0]
 [0 2 1]]
